### ISSUE TITLE
1.12.2 Crash on server

### ISSUE THREAD

**Issue by yousoenvious** [Razzokk/Wireless-Redstone#5]
crash report - https://hastebin.com/share/ejuvivutew.ruby
On client works fine but crash on server

**Comment by Razzokk** [comment]
Thanks for the report, looking into it...

**Comment by Razzokk** [comment]
Really stupid mistake here thanks a lot for reporting. It should be fixed in the newest version 1.12.2-1.1.5 and can be found [here](https://www.curseforge.com/minecraft/mc-mods/wireless-redstone-re/files/4380604). I am wondering why no one reported this issue before since it is a major oversight that happens to crash the server on startup.

Closing the issue now. Let me know if you run into any other issues....
